apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-space
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            name: mysql-persistance-storage
            mountPath: /var/lib/mysql
      volumes: 
        - name: mysql-persistance-claim
          PersistantVolumeClaim:
            claimName: mysql-pv-claim      
