apiVersion: v1 
kind: PersistantVolumeClaim
metadata:
  name: pvc-claim
  namespace: mysql 
  labels: 
    app: mysql 
spec: 
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20gi