apiVersion: v1 
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
  labels:
    app: nginx
spec: 
  selector:
    app: nginx
  type: NodePort
  port:
    protocol: TCP
    port: 80
    targetport: 80
    NodePort: 300007
    
